import React from 'react';
import Link from "next/link";

export const metadata = {
    title: process.env.NEXT_PUBLIC_APP_NAME,
    description: "Generated by create next app",
};

const LandingPage = () => {
    return (
        <main>
            <section className="flex flex-col justify-center items-center h-screen">
                <h1 className="text-4xl text-center capitalize tracking-wider">
                    Welcome to <br/> our placement <br/> website
                </h1>
                <h5 className="italic text-center text-xl my-7">
                    A one-stop platform connecting candidates, recruiters, and administrators for seamless placements.
                </h5>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    {[
                        { label: "Browse Placements", link: "#" },
                        { label: "Post a Placement", link: "#" },
                        { label: "Sign In", link: "/sign-in" },
                    ].map(({ label, link }, index) => (
                        <Link key={index} href={link} aria-label={label}>
                            <div className="border border-gray-200 shadow-md p-4 rounded-xl flex justify-center items-center hover:bg-gray-100 transition duration-200 cursor-pointer">
                                {label}
                            </div>
                        </Link>
                    ))}
                </div>
            </section>
        </main>
    );
};

export default LandingPage;
