import React from 'react';
import SignUp from "@/screens/auth/SignUp";

export const metadata = {
    title: process.env.NEXT_PUBLIC_APP_NAME + " : Sign Up",
    description: "Generated by create next app",
};

const page = () => <SignUp/>

export default page;
